### ISSUE TITLE
Reset button accessible from outside satellite

### ISSUE THREAD

**Issue by jbwillis** [PyCubed-Mini/avionics-mainboard#11]
To allow firmware updates without dissassembling, we need to make the reset button accessible from outside the satellite body. 

My thought for how to do this is to put a right angle tactile switch on the mainboard and then have a small hole that a paperclip-wide pin can be pressed through to depress the switch.

**Comment by NeilKhera** [comment]
Select a different right-angle reset button. The current one is kinda fragile
