### ISSUE TITLE
Load firmware onto current mainboard rev and run tests

### ISSUE THREAD

**Issue by jbwillis** [PyCubed-Mini/avionics-mainboard#2]
Follow instructions in `firmware` directory for loading firmware onto mainboard.

- [x] To power via USB, a jumper needs to be added to the RBF pin header.
- [x] Load firmware
- [x] See what tests already exist and run them. Ideas include I2C sniffer, neopixel flashing, reading IMU, connecting solar boards and reading sun sensor and solar controller data.

**Comment by thetazero** [comment]
[Link](https://github.com/spacecraft-design-lab-2019/avionics-motherboard/tree/zac-updates/firmware) to said firmware directory for reference:

**Comment by thetazero** [comment]
Updated the boards, and added instructions for how to do so [here](https://github.com/PyCubed-Mini/NewDocumentation/wiki/Circuit-Python#updating-the-pycubedmini-board).
Yashika's board's LED seems to work, mine appears a bit damaged and flashes and blinks here and there but works "well enough". 
Not sure how to connect the solar boards, that should probably be our next task.
